import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ContextWrapper } from "@/context/Context";
import { AddTaskModal } from "@/components/Wall/AddTaskModal";
import ModalBackground from "@/components/ModalBackground";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-full" suppressHydrationWarning>
      <ContextWrapper>
        <body className={`${inter.className} relative min-h-[90vh] pb-[5rem]`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className=" layout mx-auto relative">{children}</div>
            <AddTaskModal />
            <ModalBackground />
            <Toaster />
          </ThemeProvider>
        </body>
      </ContextWrapper>
    </html>
  );
}
